name: jwt_auth_plus
description: >
  A high-performance JWT decoder and authentication manager for Flutter. 
  Easily parse payloads, check expiration, and manage auth headers.
version: 1.0.0
repository: https://github.com/amit142857/jwt_auth_plus
homepage: https://github.com/amit142857/jwt_auth_plus

environment:
  sdk: ^3.5.0
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: